ari-py:
  python2: true
  python3: true
wazo-asterisk-config:
  bind:
    etc/asterisk/modules.conf: /etc/asterisk/modules.conf
wazo-auth:
  python3: true
  bind:
    alembic: /usr/share/wazo-auth/alembic
    etc/wazo-auth/config.yml: /etc/wazo-auth/config.yml
  clean:
    - /usr/local/bin/wazo-auth
    - /usr/local/bin/wazo-auth-init-db
    - /usr/local/bin/wazo-auth-bootstrap
wazo-auth-cli:
  python3: true
  clean:
    - /usr/local/bin/wazo-auth-cli
wazo-auth-keys:
  python3: true
  clean:
    - /usr/local/bin/wazo-auth-keys
  bind:
    etc/wazo-auth-keys/config.yml: /etc/wazo-auth-keys/config.yml
wazo-call-logd:
  python3: true
  clean:
    - /usr/local/bin/wazo-call-logd
wazo-dird:
  python3: true
  bind:
    etc/wazo-dird/config.yml: /etc/wazo-dird/config.yml
    alembic: /usr/share/wazo-dird/alembic
  clean:
    - /usr/local/bin/wazo-dird
wazo-dird-client:
  python2: true
  python3: true
wazo-res-amqp:
  clean: []
wazo-setupd:
  python3: true
  bind:
    etc/wazo-setupd/config.yml: /etc/wazo-setupd/config.yml
  clean:
    - /usr/local/bin/wazo-setupd
wazo-setupd-client:
  python3: true
xivo-agentd:
  python2: true
xivo-agid:
  python2: true
  bind:
    etc/xivo-agid/config.yml: /etc/xivo-agid/config.yml
    bin/change-pass-vm: /usr/share/asterisk/bin/change-pass-vm
xivo-amid:
  python2: true
  bind:
    etc/xivo-amid/config.yml: /etc/xivo-amid/config.yml
  clean:
    - /usr/local/bin/xivo-amid
xivo-auth-client:
  python2: true
  python3: true
xivo-bus:
  python2: true
  python3: true
xivo-confd:
  python2: true
  bind:
    etc/xivo-confd/config.yml: /etc/xivo-confd/config.yml
  clean:
    - /usr/local/bin/xivo-confd
xivo-confd-client:
  python2: true
  python3: true
xivo-confgend:
  python2: true
  bind:
    etc/xivo-confgend/config.yml: /etc/xivo-confgend/config.yml
xivo-config:
  bind:
    dialplan: /usr/share/xivo-config/dialplan
xivo-ctid:
  python2: true
  bind:
    etc/xivo-ctid/config.yml: /etc/xivo-ctid/config.yml
xivo-ctid-ng:
  python3: true
  bind:
    etc/xivo-ctid-ng/config.yml: /etc/xivo-ctid-ng/config.yml
  clean:
    - /usr/local/bin/xivo-ctid-ng
xivo-dao:
  python2: true
  python3: true
xivo-lib-python:
  python2: true
  python3: true
xivo-lib-rest-client:
  python2: true
  python3: true
wazo-libsccp:
  bind: []
xivo-manage-db:
  bind:
    alembic: /usr/share/xivo-manage-db/alembic
xivo-provisioning:
  python2: true
xivo-upgrade:
  bind:
    post-start.d: /usr/share/xivo-upgrade/post-start.d
    post-stop.d: /usr/share/xivo-upgrade/post-stop.d
    pre-start.d: /usr/share/xivo-upgrade/pre-start.d
    pre-stop.d: /usr/share/xivo-upgrade/pre-stop.d
xivo-sysconfd:
  python2: true
xivo-web-interface:
  bind:
    src: /usr/share/xivo-web-interface
