wazo-auth:
  python2: true
  bind:
    alembic: /usr/share/wazo-auth/alembic
    etc/wazo-auth/config.yml: /etc/wazo-auth/config.yml
  clean:
    - /usr/local/bin/wazo-auth
    - /usr/local/bin/wazo-auth-init-db
    - /usr/local/bin/wazo-auth-bootstrap
xivo-dao:
  python2: true
  python3: true
